import {
  Smartphone,
  Headphones,
  Tv,
  Speaker,
  Home,
  Camera,
} from "feather-icons-react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFire,
  faFireBurner,
  faComputer,
} from "@fortawesome/free-solid-svg-icons";
const cartegory = [
  {
    name: "Hot Deals",
    icon: <FontAwesomeIcon icon={faFire} className="text-red-600 h-8 w-8" />,
  },
  {
    name: "Smartphones",
    icon: <Smartphone className="h-8 w-8" />,
  },
  {
    name: "Phone Accessories",
    icon: <Headphones className="h-8 w-8" />,
  },
  {
    name: "TV & Home Theaters",
    icon: <Tv className="h-8 w-8" />,
  },
  {
    name: "Speakers",
    icon: <Speaker className="h-8 w-8" />,
  },
  {
    name: "Home Appliances",
    icon: <Home className="h-8 w-8" />,
  },
  {
    name: "Cameras",
    icon: <Camera className="h-8 w-8" />,
  },
  {
    name: "Computers",
    icon: <FontAwesomeIcon icon={faComputer} className="h-8 w-8" />,
  },
  {
    name: "Laptops",
    icon: <FontAwesomeIcon icon={faFireBurner} className="h-8 w-8" />,
  },
];

const products = [
  {
    id: 1,
    name: "Oneplus Nord 4 5G 12GB 256GB",
    price: "KSh 50,499.00",
    discount: "-14%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 AMOLED",
      rearCamera: "50MP + 8MP + 2MP",
      frontCamera: "16MP",
      processor: "Snapdragon 8+ Gen 1",
      battery: "5000mAh",
      colors: ["Black", "Blue", "Rose Gold"],
    },
    brand: "OnePlus",
    availability: "In stock",
    rating: 4.5,
  },
  {
    id: 2,
    name: "OnePlus Nord CE 4 Lite 5G 8GB 256GB",
    price: "KSh 32,499.00",
    discount: "-19%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.5 AMOLED",
      rearCamera: "48MP + 8MP + 2MP",
      frontCamera: "16MP",
      processor: "Snapdragon 8 Gen 1",
      battery: "4500mAh",
      colors: ["Black", "Blue", "Rose Gold"],
    },
    brand: "OnePlus",
    availability: "In stock",
    rating: 4.2,
  },
  {
    id: 3,
    name: "OnePlus Ace 3 16GB 1TB 5G",
    price: "KSh 81,499.00",
    discount: "-25%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.9 AMOLED",
      rearCamera: "108MP + 16MP + 5MP",
      frontCamera: "32MP",
      processor: "Snapdragon 8 Gen 2",
      battery: "6000mAh",
      colors: ["Black", "Blue", "Rose Gold"],
    },
    brand: "OnePlus",
    availability: "In stock",
    rating: 4.8,
  },
  {
    id: 4,
    name: "OnePlus Nord CE 4 8GB 256GB",
    price: "KSh 38,499.00",
    discount: "-22%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.5 AMOLED",
      rearCamera: "48MP + 8MP + 2MP",
      frontCamera: "16MP",
      processor: "Snapdragon 8 Gen 1",
      battery: "4500mAh",
      colors: ["Black", "Blue", "Rose Gold"],
    },
    brand: "OnePlus",
    availability: "In stock",
    rating: 4.3,
  },
  {
    id: 5,
    name: "Samsung Galaxy S23 Ultra",
    price: "KSh 142,999.00",
    discount: "-12%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.8 Dynamic AMOLED",
      rearCamera: "200MP + 10MP + 10MP + 12MP",
      frontCamera: "40MP",
      processor: "Exynos 2200",
      battery: "5000mAh",
      colors: ["Black", "Green", "White"],
    },
    brand: "Samsung",
    availability: "In stock",
    rating: 4.9,
  },
  {
    id: 6,
    name: "Apple iPhone 15 Pro Max 1TB",
    price: "KSh 199,999.00",
    discount: "-5%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 Super Retina XDR",
      rearCamera: "48MP + 12MP + 12MP",
      frontCamera: "12MP",
      processor: "A17 Pro",
      battery: "4352mAh",
      colors: ["Space Black", "Titanium", "White"],
    },
    brand: "Apple",
    availability: "In stock",
    rating: 4.7,
  },
  {
    id: 7,
    name: "Google Pixel 8 Pro 5G",
    price: "KSh 98,499.00",
    discount: "-10%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 OLED",
      rearCamera: "50MP + 12MP + 48MP",
      frontCamera: "10.8MP",
      processor: "Google Tensor G3",
      battery: "5000mAh",
      colors: ["Obsidian", "Snow", "Hazel"],
    },
    brand: "Google",
    availability: "In stock",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Google Pixel 8 Pro 5G",
    price: "KSh 98,499.00",
    discount: "-10%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 OLED",
      rearCamera: "50MP + 12MP + 48MP",
      frontCamera: "10.8MP",
      processor: "Google Tensor G3",
      battery: "5000mAh",
      colors: ["Obsidian", "Snow", "Hazel"],
    },
    brand: "Google",
    availability: "In stock",
    rating: 4.6,
  },
  {
    id: 9,
    name: "Google Pixel 8 Pro 5G",
    price: "KSh 98,499.00",
    discount: "-10%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 OLED",
      rearCamera: "50MP + 12MP + 48MP",
      frontCamera: "10.8MP",
      processor: "Google Tensor G3",
      battery: "5000mAh",
      colors: ["Obsidian", "Snow", "Hazel"],
    },
    brand: "Google",
    availability: "In stock",
    rating: 4.6,
  },
  {
    id: 10,
    name: "Google Pixel 8 Pro 5G",
    price: "KSh 98,499.00",
    discount: "-10%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 OLED",
      rearCamera: "50MP + 12MP + 48MP",
      frontCamera: "10.8MP",
      processor: "Google Tensor G3",
      battery: "5000mAh",
      colors: ["Obsidian", "Snow", "Hazel"],
    },
    brand: "Google",
    availability: "In stock",
    rating: 4.6,
  },
  {
    id: 11,
    name: "Google Pixel 8 Pro 5G",
    price: "KSh 98,499.00",
    discount: "-10%",
    image: "https://avechi.co.ke/mogefov/2024/08/OnePlus-Nord-4.jpg",
    description: {
      display: "6.7 OLED",
      rearCamera: "50MP + 12MP + 48MP",
      frontCamera: "10.8MP",
      processor: "Google Tensor G3",
      battery: "5000mAh",
      colors: ["Obsidian", "Snow", "Hazel"],
    },
    brand: "Google",
    availability: "In stock",
    rating: 4.6,
  },
];

const availableTags = [
  { value: "Display", label: "Display" },
  { value: "Camera", label: "Camera" },
  { value: "Front Camera", label: "Front Camera" },
  { value: "Processor", label: "Processor" },
  { value: "Battery", label: "Battery" },
  { value: "Storage", label: "Storage" },
  { value: "RAM", label: "RAM" },
  { value: "Operating System", label: "Operating System" },
  { value: "Connectivity", label: "Connectivity" },
  { value: "Weight", label: "Weight" },
  { value: "Dimensions", label: "Dimensions" },
  { value: "Audio", label: "Audio" },
  { value: "Sensors", label: "Sensors" },
  { value: "Build Quality", label: "Build Quality" },
  { value: "Warranty", label: "Warranty" },
  { value: "Color Options", label: "Color Options" },
  { value: "Price", label: "Price" },
  { value: "Reviews", label: "Reviews" },
  { value: "Brand", label: "Brand" },
  { value: "Accessories", label: "Accessories" },
];

const categories = [
  { value: "Smartphone", label: "Smartphone" },
  { value: "Headphones", label: "Headphones" },
  { value: "TV", label: "TV" },
  { value: "Speaker", label: "Speaker" },
  { value: "Home", label: "Home" },
  { value: "Camera", label: "Camera" },
  { value: "Computer", label: "Computer" },
  { value: "Laptop", label: "Laptop" },
  { value: "Tablet", label: "Tablet" },
  { value: "Smartwatch", label: "Smartwatch" },
];

export { cartegory, products, availableTags, categories };
