// src/GlobalIcons.js
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import PropTypes from "prop-types";
import {
  faTrashAlt,
  faPlus,
  faEdit,
  faFire,
  faIcons,
  faTv,
  faDesktop,
  faMobileAlt,
  faHome,
  faCamera,
  faBlender,
  faLaptop,
  faBriefcase,
  faHeadphones,
  faTabletAlt,
  faGamepad,
  faPlug,
  faBatteryFull,
  faSdCard,
  faNetworkWired,
  faWifi,
  faHeart,
  faShoppingCart,
  faUser,
  faSignOutAlt,
  faBell,
  faCreditCard,
  faMoneyBillWave,
  faHeartBroken,
  faStar,
  faStarHalfAlt,
  faCommentAlt,
  faTags,
  faPercent,
  faQuestionCircle,
  faLifeRing,
  faFilter,
  faSortAmountDown,
  faSortAmountUp,
  faListAlt,
  faThLarge,
  faBars,
  faWallet,
  faMapMarkerAlt,
  faClock,
  faTruck,
  faReceipt,
  faFileInvoice,
  faBatteryHalf,
  faBatteryQuarter,
  faPowerOff,
  faShareAlt,
} from "@fortawesome/free-solid-svg-icons";

export const icons = [
  { id: "trash", name: "Trash", icon: faTrashAlt, var: "faTrashAlt" },
  { id: "plus", name: "Plus", icon: faPlus, var: "faPlus" },
  { id: "edit", name: "Edit", icon: faEdit, var: "faEdit" },
  { id: "hotDeal", name: "Hot Deal", icon: faFire, var: "faFire" },
  { id: "defaultIcon", name: "Default Icon", icon: faIcons, var: "faIcons" },
  { id: "tv", name: "TV", icon: faTv, var: "faTv" },
  { id: "computer", name: "Computer", icon: faDesktop, var: "faDesktop" },
  {
    id: "smartphone",
    name: "Smartphone",
    icon: faMobileAlt,
    var: "faMobileAlt",
  },
  { id: "home", name: "Home", icon: faHome, var: "faHome" },
  { id: "camera", name: "Camera", icon: faCamera, var: "faCamera" },
  { id: "kitchen", name: "Kitchen", icon: faBlender, var: "faBlender" },
  { id: "laptop", name: "Laptop", icon: faLaptop, var: "faLaptop" },
  { id: "office", name: "Office", icon: faBriefcase, var: "faBriefcase" },
  {
    id: "headphones",
    name: "Headphones",
    icon: faHeadphones,
    var: "faHeadphones",
  },
  { id: "tablet", name: "Tablet", icon: faTabletAlt, var: "faTabletAlt" },
  { id: "gaming", name: "Gaming", icon: faGamepad, var: "faGamepad" },
  { id: "accessories", name: "Accessories", icon: faPlug, var: "faPlug" },
  { id: "battery", name: "Battery", icon: faBatteryFull, var: "faBatteryFull" },
  { id: "sdCard", name: "SD Card", icon: faSdCard, var: "faSdCard" },
  {
    id: "network",
    name: "Network",
    icon: faNetworkWired,
    var: "faNetworkWired",
  },
  { id: "wifi", name: "WiFi", icon: faWifi, var: "faWifi" },
  { id: "wishlist", name: "Wishlist", icon: faHeart, var: "faHeart" },
  { id: "cart", name: "Cart", icon: faShoppingCart, var: "faShoppingCart" },
  { id: "user", name: "User", icon: faUser, var: "faUser" },
  { id: "logout", name: "Logout", icon: faSignOutAlt, var: "faSignOutAlt" },
  { id: "notifications", name: "Notifications", icon: faBell, var: "faBell" },
  { id: "checkout", name: "Checkout", icon: faCreditCard, var: "faCreditCard" },
  { id: "cash", name: "Cash", icon: faMoneyBillWave, var: "faMoneyBillWave" },
  {
    id: "removeWishlist",
    name: "Remove Wishlist",
    icon: faHeartBroken,
    var: "faHeartBroken",
  },
  { id: "rating", name: "Rating", icon: faStar, var: "faStar" },
  {
    id: "halfStar",
    name: "Half Star",
    icon: faStarHalfAlt,
    var: "faStarHalfAlt",
  },
  { id: "reviews", name: "Reviews", icon: faCommentAlt, var: "faCommentAlt" },
  { id: "discount", name: "Discount", icon: faTags, var: "faTags" },
  { id: "sale", name: "Sale", icon: faPercent, var: "faPercent" },
  { id: "help", name: "Help", icon: faQuestionCircle, var: "faQuestionCircle" },
  { id: "support", name: "Support", icon: faLifeRing, var: "faLifeRing" },
  { id: "filter", name: "Filter", icon: faFilter, var: "faFilter" },
  {
    id: "sortDown",
    name: "Sort Down",
    icon: faSortAmountDown,
    var: "faSortAmountDown",
  },
  {
    id: "sortUp",
    name: "Sort Up",
    icon: faSortAmountUp,
    var: "faSortAmountUp",
  },
  { id: "categories", name: "Categories", icon: faListAlt, var: "faListAlt" },
  { id: "gridView", name: "Grid View", icon: faThLarge, var: "faThLarge" },
  { id: "listView", name: "List View", icon: faBars, var: "faBars" },
  { id: "wallet", name: "Wallet", icon: faWallet, var: "faWallet" },
  {
    id: "location",
    name: "Location",
    icon: faMapMarkerAlt,
    var: "faMapMarkerAlt",
  },
  { id: "deliveryTime", name: "Delivery Time", icon: faClock, var: "faClock" },
  { id: "shipping", name: "Shipping", icon: faTruck, var: "faTruck" },
  { id: "invoice", name: "Invoice", icon: faFileInvoice, var: "faFileInvoice" },
  { id: "receipt", name: "Receipt", icon: faReceipt, var: "faReceipt" },
  {
    id: "batteryHalf",
    name: "Battery Half",
    icon: faBatteryHalf,
    var: "faBatteryHalf",
  },
  {
    id: "batteryQuarter",
    name: "Battery Quarter",
    icon: faBatteryQuarter,
    var: "faBatteryQuarter",
  },
  { id: "power", name: "Power", icon: faPowerOff, var: "faPowerOff" },
  { id: "share", name: "Share", icon: faShareAlt, var: "faShareAlt" },
];

const GlobalIcon = ({ icon, ...props }) => {
  const IconComponent = icons.find((i) => i.var === icon)?.icon;

  return IconComponent ? (
    <FontAwesomeIcon icon={IconComponent} {...props} />
  ) : null;
};

GlobalIcon.propTypes = {
  icon: PropTypes.oneOf(icons.map((iconObj) => iconObj.var)).isRequired,
};

export default GlobalIcon;
