// src/GlobalIcons.js
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import PropTypes from "prop-types";
import {
  faTrashAlt,
  faPlus,
  faEdit,
  faFire,
  faIcons,
  faTv,
  faDesktop,
  faMobileAlt,
  faHome,
  faCamera,
  faBlender,
  faLaptop,
  faBriefcase,
  faHeadphones,
  faTabletAlt,
  faGamepad,
  faPlug,
  faBatteryFull,
  faSdCard,
  faNetworkWired,
  faWifi,
  faHeart,
  faShoppingCart,
  faUser,
  faSignOutAlt,
  faBell,
  faCreditCard,
  faMoneyBillWave,
  faHeartBroken,
  faStar,
  faStarHalfAlt,
  faCommentAlt,
  faTags,
  faPercent,
  faQuestionCircle,
  faLifeRing,
  faFilter,
  faSortAmountDown,
  faSortAmountUp,
  faListAlt,
  faThLarge,
  faBars,
  faWallet,
  faMapMarkerAlt,
  faClock,
  faTruck,
  faReceipt,
  faFileInvoice,
  faBatteryHalf,
  faBatteryQuarter,
  faPowerOff,
  faShareAlt,
} from "@fortawesome/free-solid-svg-icons";

export const icons = [
  { id: "trash", name: "Trash", icon: faTrashAlt },
  { id: "plus", name: "Plus", icon: faPlus },
  { id: "edit", name: "Edit", icon: faEdit },
  { id: "hotDeal", name: "Hot Deal", icon: faFire },
  { id: "defaultIcon", name: "Default Icon", icon: faIcons },
  { id: "tv", name: "TV", icon: faTv },
  { id: "computer", name: "Computer", icon: faDesktop },
  { id: "smartphone", name: "Smartphone", icon: faMobileAlt },
  { id: "home", name: "Home", icon: faHome },
  { id: "camera", name: "Camera", icon: faCamera },
  { id: "kitchen", name: "Kitchen", icon: faBlender },
  { id: "laptop", name: "Laptop", icon: faLaptop },
  { id: "office", name: "Office", icon: faBriefcase },
  { id: "headphones", name: "Headphones", icon: faHeadphones },
  { id: "tablet", name: "Tablet", icon: faTabletAlt },
  { id: "gaming", name: "Gaming", icon: faGamepad },
  { id: "accessories", name: "Accessories", icon: faPlug },
  { id: "battery", name: "Battery", icon: faBatteryFull },
  { id: "sdCard", name: "SD Card", icon: faSdCard },
  { id: "network", name: "Network", icon: faNetworkWired },
  { id: "wifi", name: "WiFi", icon: faWifi },
  { id: "wishlist", name: "Wishlist", icon: faHeart },
  { id: "cart", name: "Cart", icon: faShoppingCart },
  { id: "user", name: "User", icon: faUser },
  { id: "logout", name: "Logout", icon: faSignOutAlt },
  { id: "notifications", name: "Notifications", icon: faBell },
  { id: "checkout", name: "Checkout", icon: faCreditCard },
  { id: "cash", name: "Cash", icon: faMoneyBillWave },
  { id: "removeWishlist", name: "Remove Wishlist", icon: faHeartBroken },
  { id: "rating", name: "Rating", icon: faStar },
  { id: "halfStar", name: "Half Star", icon: faStarHalfAlt },
  { id: "reviews", name: "Reviews", icon: faCommentAlt },
  { id: "discount", name: "Discount", icon: faTags },
  { id: "sale", name: "Sale", icon: faPercent },
  { id: "help", name: "Help", icon: faQuestionCircle },
  { id: "support", name: "Support", icon: faLifeRing },
  { id: "filter", name: "Filter", icon: faFilter },
  { id: "sortDown", name: "Sort Down", icon: faSortAmountDown },
  { id: "sortUp", name: "Sort Up", icon: faSortAmountUp },
  { id: "categories", name: "Categories", icon: faListAlt },
  { id: "gridView", name: "Grid View", icon: faThLarge },
  { id: "listView", name: "List View", icon: faBars },
  { id: "wallet", name: "Wallet", icon: faWallet },
  { id: "location", name: "Location", icon: faMapMarkerAlt },
  { id: "deliveryTime", name: "Delivery Time", icon: faClock },
  { id: "shipping", name: "Shipping", icon: faTruck },
  { id: "invoice", name: "Invoice", icon: faFileInvoice },
  { id: "receipt", name: "Receipt", icon: faReceipt },
  { id: "batteryHalf", name: "Battery Half", icon: faBatteryHalf },
  { id: "batteryQuarter", name: "Battery Quarter", icon: faBatteryQuarter },
  { id: "power", name: "Power", icon: faPowerOff },
  { id: "share", name: "Share", icon: faShareAlt },
];

// Component to render an icon based on the id
const GlobalIcon = ({ icon, ...props }) => {
  // Find the icon object by matching the `id`
  const IconComponent = icons.find((i) => i.id === icon)?.icon;

  return IconComponent ? (
    <FontAwesomeIcon icon={IconComponent} {...props} />
  ) : null;
};

// Validate `icon` prop to only accept IDs in the icons array
GlobalIcon.propTypes = {
  icon: PropTypes.oneOf(icons.map((iconObj) => iconObj.id)).isRequired,
};

export default GlobalIcon;
